version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "5000:5000"

  films:
    container_name: films
    restart: always
    build: ./films_api
    ports:
      - "5001:5001"

  characters:
    container_name: characters
    restart: always
    build: ./characters_api
    ports:
      - "5002:5002"
  
  planets:
    container_name: planets
    restart: always
    build: ./planets_api
    ports:
      - "5003:5003"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "5005:5005"